login:
  excludePathPatterns:
    - /user/register
    - /user/registerByWechat
    - /user/registerImUser
    - /user/registerGroup
    - /user/login
    - /user/loginByCode
    - /user/loginByCaptcha
    - /user/loginByWeChat
    - /user/loginByWeChat4MP
    - /user/login/auto
    - /user/loginBuyCareOrder
    - /user/get
    - /user/password/reset
    - /user/resetPhoneAndPassword
    - /user/password/update
    - /user/getWeChatStatus
    - /user/getWeChatStatus4MP
    - /user/isBindWechat
    - /sms/randcode/getSMSCode
    - /sms/randcode/getVoiceCode
    - /sms/randcode/verifyCode
    - /conference/endCall
    - /sms/verify/telephone
    - /sms/verify/isJoinHospital
    - /b/circle/msg/hot
    - /b/circle/msg/latest
    - /b/circle/msg/get
    - /b/circle/msg/comment/list
    - /b/circle/msg/square
    - /config
    - /getQiniuToken
    - /qr/scanning
    - /qr/generateScan
    - /qr/wxQrScanning
    - /qr/circleQrcodeScan
    - /user/preResetPassword
    - /user/preResetPasswordVoiceCode
    - /user/sendRanCode
    - /user/verifyResetPassword
    - /user/resetPassword
    - /user/findSmsCodeById
    - /base/*
    - /monitor/*
    - /company/registerCompany
    - /pack/order/submitCareOrder
    - /pack/carePlan/findDoctorGroupByPackId
    - /pack/pack/findDoctorGroupByPackId
    - /pack/order/getAppointmentOrder4H5
    - /voip/endCall
    - /pack/paynotify/alipaycallback
    - /pack/paynotify/wxpaycallback
    - /pack/refundnotify/alipaycallback
    - /wx/*
    - /groupSearch/findAllDoctor
    - /pack/carePlan/findCarePlanInfo
    - /company/user/confirmByCompany
    - /group/user/confirmByJoin
    - /group/doctor/getInviteGroupDoctors
    - /group/doctor/saveCompleteByGroupDoctor
    - /company/user/companyLogin
    - /group/user/getInviteStatus
    - /group/hospital/getGroupHospitalByTelephone
    - /group/hospital/confirmByRegisterJoin
    - /group/hospital/confirmByJoin
    - /group/hospital/completeJoinHospital
    - /group/hospital/updateUnauthUserMessage
    - /base/getDepts
    - /base/getTitles
    - /inner_api/**
    - /drugEnterprise/addEnterPriseInfo
    - /drugEnterprise/deleteEnterPriseInfo
    - /drugEnterprise/addGoodsInfo
    - /drugEnterprise/deleteGoodsInfo
    - /inner/pub/getPubGroups
    - /inner/pub/getPubs
    - /inner/pub/sendMsg
    - /pub/sendMsg
    - /common/getServerTime
    - /user/getGuestToken
    - /groupSearch/findOrderDoctor
    - /groupSearch/getDoctorsByPackType
    - /groupSearch/findAllGroup
    - /groupSearch/findRecommDisease
    - /groupSearch/findGroupBaseInfo
    - /groupSearch/findDoctorByGroupForPatient
    - /groupSearch/getDoctorsByDiseaseId
    - /doctor/basicInfo
    - /doctor/getIntro
    - /pack/pack/query
    - /pack/evaluate/getTopSix
    - /pack/evaluate/getEvaluationDetail
    - /base/getOneLevelDisease
    - /groupSearch/findDoctorByDisease
    - /groupSearch/findDoctoreByKeyWord
    - /pack/order/findOrderSchedule
    - /pack/carePlan/queryCarePlanByOne
    - /appService/getVersion
    - /knowledge/getGroupMedicalKnowledgeList
    - /dynamic/getGroupAndDoctorDynamicListByGroupId
    - /group/getGroupExistRegion
    - /groupSearch/getDeptsWithDoc
    - /groupSearch/findDoctorByGroupForPatient
    - /dynamic/getDoctorDynamicListByDoctorId
    - /group/getGroupRecommendedList
    - /diseaseType/getCommonDiseases
    - /diseaseType/findByKeyword
    - /diseaseType/findById
    - /recommend/getRecommendDocList
    - /integralDoctor/getIntegralDoctorList
    - /upatedate/**
    - /vpanfile/queryFile
    - /geoNear/findDoctorByLocation
    - /geoNear/findDoctorByCondition
    - /geoNear/getAllGeoDepts
    - /wx/feedback/saveFeedback
    - /vpanfile/getUploadToken
    - /api/*
    - /base/getAllAreas
    - /base/getAllDepts
  guestIncludePathPatterns:
    - /document/getDocumentList
    - /groupSearch/findOnDutyToday
    - /groupSearch/findAppointmentDoctor
    - /document/viewDocumentDetail
    - /groupSearch/groupOnlineDoctors
    - /groupSearch/findGroupByDisease
    - /groupSearch/findGroupByKeyWord
    - /user/get
    - /pack/pack/get
    - /guide/exist
    - /pack/orderExpand/get3Schedule
    - /knowledge/getDoctorMedicalKnowledgeList
    - /knowledge/getUrlById
    - /autoDiagnose/getBodyPartsList
    - /autoDiagnose/getDiseaseList
    - /groupSearch/findGroupByDiseaseIds
    - /groupSearch/getDoctorsByDiseaseIds